### ISSUE TITLE
RecordCassandraSinkTask fails from a localrun sink

### ISSUE THREAD

**Issue by lhotari** [datastax/pulsar-sink#18]
From the reporter: "I'm trying to write data to Astra DB from a localrun sink using com.datastax.oss.sink.pulsar.RecordCassandraSinkTask and I'm getting the following exception.  It works fine if I use StringCassandraSinkTask instead. "

Stacktrace:
```
java.util.concurrent.CompletionException: java.lang.IncompatibleClassChangeError: Found interface org.apache.pulsar.common.schema.SchemaInfo, but class was expected
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.apache.pulsar.common.schema.SchemaInfo, but class was expected
	at com.datastax.oss.sink.pulsar.LocalSchemaRegistry.computeRecordSchemaPath(LocalSchemaRegistry.java:40) ~[cassandra-sink-pulsar-1.4.0.jar:?]
	at com.datastax.oss.sink.pulsar.LocalSchemaRegistry.ensureAndUpdateSchema(LocalSchemaRegistry.java:31) ~[cassandra-sink-pulsar-1.4.0.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarStruct.ofRecord(PulsarStruct.java:52) ~[cassandra-sink-pulsar-1.4.0.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarSinkRecordImpl.value(PulsarSinkRecordImpl.java:86) ~[cassandra-sink-pulsar-1.4.0.jar:?]
	at com.datastax.oss.common.sink.AbstractSinkTask.mapAndQueueRecord(AbstractSinkTask.java:199) ~[cassandra-sink-pulsar-1.4.0.jar:?]
	at com.datastax.oss.common.sink.AbstractSinkTask.lambda$put$1(AbstractSinkTask.java:108) ~[cassandra-sink-pulsar-1.4.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
```

**Comment by lhotari** [comment]
There are breaking changes in Pulsar 2.8.x . @eolivelli Is Pulsar 2.8.x supported for the Cassandra Sink project?

**Comment by lhotari** [comment]
Related to https://github.com/apache/pulsar/issues/11338 ?

**Comment by nicoloboschi** [comment]
@lhotari yes, I think the cause is the PR you mentioned. pulsar-sink is built using Apache Pulsar 2.6.2, so it should work only with 2.6.x and 2.7.x. 

In order to support Pulsar 2.8.x we need to upgrade the dependency

**Comment by eolivelli** [comment]
We have to cut a new release built for 2.8+

I already opened a ticket to fully support KeyValue schema.
The changes should be simple.

Please also note that Sink<GenericRecord> in Pulsar 2.8+ has a different meaning because AUTO_CONSUME schema deals with every Schema not only Avro/json.
So we will have to support all the data types

**Comment by eolivelli** [comment]
BTW you can use Luna Streaming 2.8 instead of Pulsar 2.8 and it ahould work

**Comment by nicoloboschi** [comment]
Starting from 1.5.0, Pulsar 2.8+ (or Luna Streaming 2.8+) is needed
