### ISSUE TITLE
Support map/list CQ data types for Avro serialized pulsar messages

### ISSUE THREAD

**Issue by aymkhalil** [datastax/pulsar-sink#33]
**Scenario**
 * Create a C* table with map (or list) CQL type
 * Send a POJO with map field mapped to C* via a Pulsar producer with Avro schema
 * The sink will fail with "UnsupportedOperationException":
 ```
2022-07-11T16:24:22,337+0000 [mapping-1] WARN  com.datastax.oss.sink.pulsar.CassandraSinkTask - Error decoding/mapping Pulsar record PulsarSinkRecord{SinkRecord(sourceRecord=PulsarRecord(topicName=Optional[persistent://public/default/mytopic], partition=0, message=Optional[org.apache.pulsar.client.impl.MessageImpl@6a10cfb0], schema=AUTO_CONSUME({schemaVersion=,schemaType=BYTES}{schemaVersion=\x00\x00\x00\x00\x00\x00\x00\x00,schemaType=AVRO}), failFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$477/0x0000000100708440@10ccac96, ackFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$476/0x0000000100708040@f8d3dc0), value=org.apache.pulsar.client.impl.schema.generic.GenericAvroRecord@4d887e1e)}: type class org.apache.avro.generic.GenericData$Array
2022-07-11T16:24:22,338+0000 [mapping-1] WARN  com.datastax.oss.sink.pulsar.CassandraSinkTask - Details of the error
java.lang.UnsupportedOperationException: type class org.apache.avro.generic.GenericData$Array
	at com.datastax.oss.sink.pulsar.PulsarSchema.of(PulsarSchema.java:84) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarSchema.update(PulsarSchema.java:131) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarSchema.<init>(PulsarSchema.java:100) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarSchema.createFromStruct(PulsarSchema.java:89) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.sink.pulsar.LocalSchemaRegistry.ensureAndUpdateSchema(LocalSchemaRegistry.java:58) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarStruct.ofRecord(PulsarStruct.java:68) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarSinkRecordImpl.unwrap(PulsarSinkRecordImpl.java:114) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.sink.pulsar.PulsarSinkRecordImpl.value(PulsarSinkRecordImpl.java:132) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.common.sink.AbstractSinkTask.mapAndQueueRecord(AbstractSinkTask.java:199) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.common.sink.AbstractSinkTask.lambda$put$1(AbstractSinkTask.java:108) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-07-11T16:24:22,338+0000 [mapping-1] INFO  com.datastax.oss.sink.pulsar.CassandraSinkTask - fail record PulsarSinkRecord{SinkRecord(sourceRecord=PulsarRecord(topicName=Optional[persistent://public/default/mytopic], partition=0, message=Optional[org.apache.pulsar.client.impl.MessageImpl@6a10cfb0], schema=AUTO_CONSUME({schemaVersion=,schemaType=BYTES}{schemaVersion=\x00\x00\x00\x00\x00\x00\x00\x00,schemaType=AVRO}), failFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$477/0x0000000100708440@10ccac96, ackFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$476/0x0000000100708040@f8d3dc0), value=org.apache.pulsar.client.impl.schema.generic.GenericAvroRecord@4d887e1e)} due to java.lang.UnsupportedOperationException: type class org.apache.avro.generic.GenericData$Array
```

**Comment by aymkhalil** [comment]
Things to consider:
* Generic types of the Map k/v or Array v may have to be resolved at runtime - this is so the generic types [here](https://github.com/datastax/messaging-connectors-commons/blob/7a798133e8180c12a6a73e066d123074239f50ec/common/src/main/java/com/datastax/oss/common/sink/record/StructDataMetadataSupport.java#L48). If we naively pass a Map or Array pulsar schema type to this code, it will hang in an infinite loop (getGenericType -> getGenericType). Also consider adding safeguards to prevent an infinite loop anyway.
* Convert avro utf8 to string at the sink level (I tried with C* type codecs/converting codecs to do avro utf8 -> text cql types and it doesn't seem the way to go). Here is the exception if we were to pass the Avro type as is:
```
Invalid type for key: class org.apache.avro.util.Utf8
2022-07-12T00:51:05,742+0000 [mapping-0] WARN  com.datastax.oss.sink.pulsar.CassandraSinkTask - Details of the error
java.lang.IllegalArgumentException: Invalid type for key: class org.apache.avro.util.Utf8
	at com.datastax.oss.driver.internal.core.type.codec.MapCodec.encode(MapCodec.java:95) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.driver.internal.core.type.codec.MapCodec.encode(MapCodec.java:30) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.dsbulk.codecs.api.ConvertingCodec.encode(ConvertingCodec.java:71) ~[dsbulk-codecs-api-1.6.0.jar:?]
	at com.datastax.oss.common.sink.RecordMapper.bindColumn(RecordMapper.java:299) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.common.sink.RecordMapper.bindColumnsToBuilder(RecordMapper.java:203) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.common.sink.RecordMapper.map(RecordMapper.java:122) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.common.sink.AbstractSinkTask.mapAndQueueRecord(AbstractSinkTask.java:211) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at com.datastax.oss.common.sink.AbstractSinkTask.lambda$put$1(AbstractSinkTask.java:108) ~[cassandra-sink-pulsar-1.6.4-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-07-12T00:51:05,747+0000 [mapping-0] INFO  com.datastax.oss.sink.pulsar.CassandraSinkTask - fail record PulsarSinkRecord{SinkRecord(sourceRecord=PulsarRecord(topicName=Optional[persistent://public/default/mytopic], partition=0, message=Optional[org.apache.pulsar.client.impl.MessageImpl@38ae51b4], schema=AUTO_CONSUME({schemaVersion=,schemaType=BYTES}{schemaVersion=\x00\x00\x00\x00\x00\x00\x00\x00,schemaType=AVRO}), failFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$478/0x0000000100708840@c66d6ee, ackFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$477/0x0000000100708440@258cda21), value=org.apache.pulsar.client.impl.schema.generic.GenericAvroRecord@67b6a877)} due to java.lang.IllegalArgumentException: Invalid type for key: class org.apache.avro.util.Utf8
```

**Comment by nicoloboschi** [comment]
@aymkhalil in ElasticSearch Sink we did something similar recently https://github.com/apache/pulsar/pull/15430
