### ISSUE TITLE
Cannot deal with schema-less topics

### ISSUE THREAD

**Issue by eolivelli** [datastax/pulsar-sink#8]
Sending data to a topic using a schema less produce (a Go-client) results in this error, even with the -classname com.datastax.oss.sink.pulsar.StringCassandraSinkTask processor

04:33:28.213 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - [id: 0x2d2a25ef, L:/10.101.35.193:54296 - R:ip-10-101-35-60.srv101.dsinternal.org/10.101.35.60:6550] Received error from server: Topic does not have schema to check
04:33:28.215 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/perf_topic][dse-sink-perf] Failed to subscribe to topic on ip-10-101-35-60.srv101.dsinternal.org/10.101.35.60:6550
04:33:28.216 [public/default/dse-sink-perf-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - Source open produced uncaught exception:
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: Topic does not have schema to check
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:777) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:615) ~[org.apache.pulsar-pulsar-client-original-2.6.2.jar:2.6.2]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:190) ~[org.apache.pulsar-pulsar-common-2.6.2.jar:2.6.2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]

**Comment by eolivelli** [comment]
resolved
